name: Build & Deploy Pages (with runtime data)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare dist
        run: |
          mkdir -p dist
          cp index.html style.css script.js .nojekyll dist/

      - name: Fetch masked data from GAS
        env:
          GAS_EXEC_URL: ${{ secrets.GAS_EXEC_URL }}
          GAS_KEY: ${{ secrets.GAS_KEY }}
        run: |
          set -e
          URL="${GAS_EXEC_URL}"
          if [ -n "${GAS_KEY}" ]; then
            URL="${URL}?key=${GAS_KEY}&limit=500&order=asc"
          fi
          curl -sSL "$URL" -o dist/data.json
          test -s dist/data.json
          node -e "JSON.parse(require('fs').readFileSync('dist/data.json','utf8'))"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
